//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, ExpressionUtils } from "@zenstackhq/orm/schema";
export class SchemaType implements SchemaDef {
    provider = {
        type: "postgresql"
    } as const;
    models = {
        User: {
            name: "User",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }],
                    default: ExpressionUtils.call("cuid")
                },
                string: {
                    name: "string",
                    type: "String",
                    optional: true
                },
                stringArray: {
                    name: "stringArray",
                    type: "String",
                    array: true
                },
                boolean: {
                    name: "boolean",
                    type: "Boolean",
                    optional: true
                },
                booleanArray: {
                    name: "booleanArray",
                    type: "Boolean",
                    array: true
                },
                int: {
                    name: "int",
                    type: "Int",
                    optional: true
                },
                intArray: {
                    name: "intArray",
                    type: "Int",
                    array: true
                },
                float: {
                    name: "float",
                    type: "Float",
                    optional: true
                },
                floatArray: {
                    name: "floatArray",
                    type: "Float",
                    array: true
                },
                dateTime: {
                    name: "dateTime",
                    type: "DateTime",
                    optional: true
                },
                bigInt: {
                    name: "bigInt",
                    type: "BigInt",
                    optional: true
                },
                bigIntArray: {
                    name: "bigIntArray",
                    type: "BigInt",
                    array: true
                },
                enum: {
                    name: "enum",
                    type: "Role"
                },
                json: {
                    name: "json",
                    type: "Meta",
                    optional: true,
                    attributes: [{ name: "@json" }]
                },
                posts: {
                    name: "posts",
                    type: "Post",
                    array: true,
                    relation: { opposite: "author" }
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        },
        Post: {
            name: "Post",
            fields: {
                id: {
                    name: "id",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("cuid") }] }],
                    default: ExpressionUtils.call("cuid")
                },
                createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    updatedAt: true,
                    attributes: [{ name: "@updatedAt" }]
                },
                title: {
                    name: "title",
                    type: "String"
                },
                content: {
                    name: "content",
                    type: "String"
                },
                published: {
                    name: "published",
                    type: "Boolean",
                    attributes: [{ name: "@default", args: [{ name: "value", value: ExpressionUtils.literal(false) }] }],
                    default: false
                },
                author: {
                    name: "author",
                    type: "User",
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array("String", [ExpressionUtils.field("authorId")]) }, { name: "references", value: ExpressionUtils.array("String", [ExpressionUtils.field("id")]) }] }],
                    relation: { opposite: "posts", fields: ["authorId"], references: ["id"] }
                },
                authorId: {
                    name: "authorId",
                    type: "String",
                    foreignKeyFor: [
                        "author"
                    ]
                }
            },
            idFields: ["id"],
            uniqueFields: {
                id: { type: "String" }
            }
        }
    } as const;
    typeDefs = {
        Meta: {
            name: "Meta",
            fields: {
                string: {
                    name: "string",
                    type: "String",
                    optional: true
                },
                stringArray: {
                    name: "stringArray",
                    type: "String",
                    array: true
                },
                boolean: {
                    name: "boolean",
                    type: "Boolean",
                    optional: true
                },
                booleanArray: {
                    name: "booleanArray",
                    type: "Boolean",
                    array: true
                },
                int: {
                    name: "int",
                    type: "Int",
                    optional: true
                },
                intArray: {
                    name: "intArray",
                    type: "Int",
                    array: true
                },
                float: {
                    name: "float",
                    type: "Float",
                    optional: true
                },
                floatArray: {
                    name: "floatArray",
                    type: "Float",
                    array: true
                },
                enum: {
                    name: "enum",
                    type: "Role",
                    optional: true
                },
                dateTime: {
                    name: "dateTime",
                    type: "DateTime"
                }
            }
        }
    } as const;
    enums = {
        Role: {
            name: "Role",
            values: {
                USER: "USER",
                ADMIN: "ADMIN"
            }
        }
    } as const;
    authType = "User" as const;
    plugins = {};
}
export const schema = new SchemaType();
