//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, ExpressionUtils } from '@zenstackhq/orm/schema'
export class SchemaType implements SchemaDef {
  provider = {
    type: 'sqlite',
  } as const
  models = {
    User: {
      name: 'User',
      fields: {
        id: {
          name: 'id',
          type: 'String',
          id: true,
          attributes: [
            { name: '@id' },
            { name: '@default', args: [{ name: 'value', value: ExpressionUtils.call('cuid') }] },
          ],
          default: ExpressionUtils.call('cuid'),
        },
        string: {
          name: 'string',
          type: 'String',
          optional: true,
        },
        stringArray: {
          name: 'stringArray',
          type: 'String',
          array: true,
          optional: true,
        },
        boolean: {
          name: 'boolean',
          type: 'Boolean',
          optional: true,
        },
        booleanArray: {
          name: 'booleanArray',
          type: 'Boolean',
          array: true,
          optional: true,
        },
        int: {
          name: 'int',
          type: 'Int',
          optional: true,
        },
        intArray: {
          name: 'intArray',
          type: 'Int',
          array: true,
          optional: true,
        },
        float: {
          name: 'float',
          type: 'Float',
          optional: true,
        },
        floatArray: {
          name: 'floatArray',
          type: 'Float',
          optional: true,
          array: true,
        },
        dateTime: {
          name: 'dateTime',
          type: 'DateTime',
          optional: true,
        },
        // dateTimeArray: {
        //   name: 'dateTime',
        //   type: 'DateTime',
        //   optional: true,
        //   array: true,
        // },
        bigInt: {
          name: 'bigInt',
          type: 'BigInt',
          optional: true,
        },
        bigIntArray: {
          name: 'bigIntArray',
          type: 'BigInt',
          optional: true,
          array: true,
        },
        enum: {
          name: 'enum',
          type: 'Role',
          attributes: [
            { name: '@default', args: [{ name: 'value', value: ExpressionUtils.literal('USER') }] },
          ],
          default: 'USER',
        },
        // enumArray: {
        //   name: 'enumArray',
        //   type: 'Role',
        //   array: true,
        //   attributes: [
        //     { name: '@default', args: [{ name: 'value', value: ExpressionUtils.literal('USER') }] },
        //   ],
        //   default: 'USER',
        // },
        posts: {
          name: 'posts',
          type: 'Post',
          array: true,
          relation: { opposite: 'author' },
        },
        profile: {
          name: 'profile',
          type: 'Profile',
          optional: true,
          relation: { opposite: 'user' },
        },
        json: {
          name: 'json',
          type: 'Json',
          optional: true,
        },
      },
      attributes: [
        {
          name: '@@allow',
          args: [
            { name: 'operation', value: ExpressionUtils.literal('all') },
            {
              name: 'condition',
              value: ExpressionUtils.binary(
                ExpressionUtils.member(ExpressionUtils.call('auth'), ['id']),
                '==',
                ExpressionUtils.field('id'),
              ),
            },
          ],
        },
        {
          name: '@@allow',
          args: [
            { name: 'operation', value: ExpressionUtils.literal('read') },
            {
              name: 'condition',
              value: ExpressionUtils.binary(
                ExpressionUtils.call('auth'),
                '!=',
                ExpressionUtils._null(),
              ),
            },
          ],
        },
      ],
      idFields: ['id'],
      uniqueFields: {
        id: { type: 'String' },
      },
    },
    Post: {
      name: 'Post',
      fields: {
        id: {
          name: 'id',
          type: 'String',
          id: true,
          attributes: [
            { name: '@id' },
            { name: '@default', args: [{ name: 'value', value: ExpressionUtils.call('cuid') }] },
          ],
          default: ExpressionUtils.call('cuid'),
        },
        createdAt: {
          name: 'createdAt',
          type: 'DateTime',
          attributes: [
            { name: '@default', args: [{ name: 'value', value: ExpressionUtils.call('now') }] },
          ],
          default: ExpressionUtils.call('now'),
        },
        updatedAt: {
          name: 'updatedAt',
          type: 'DateTime',
          updatedAt: true,
          attributes: [{ name: '@updatedAt' }],
        },
        title: {
          name: 'title',
          type: 'String',
        },
        content: {
          name: 'content',
          type: 'String',
          optional: true,
        },
        published: {
          name: 'published',
          type: 'Boolean',
          attributes: [
            { name: '@default', args: [{ name: 'value', value: ExpressionUtils.literal(false) }] },
          ],
          default: false,
        },
        author: {
          name: 'author',
          type: 'User',
          attributes: [
            {
              name: '@relation',
              args: [
                {
                  name: 'fields',
                  value: ExpressionUtils.array([ExpressionUtils.field('authorId')]),
                },
                { name: 'references', value: ExpressionUtils.array([ExpressionUtils.field('id')]) },
                { name: 'onUpdate', value: ExpressionUtils.literal('Cascade') },
                { name: 'onDelete', value: ExpressionUtils.literal('Cascade') },
              ],
            },
          ],
          relation: {
            opposite: 'posts',
            fields: ['authorId'],
            references: ['id'],
            onUpdate: 'Cascade',
            onDelete: 'Cascade',
          },
        },
        authorId: {
          name: 'authorId',
          type: 'String',
          foreignKeyFor: ['author'],
        },
        comments: {
          name: 'comments',
          type: 'Comment',
          array: true,
          relation: { opposite: 'post' },
        },
      },
      attributes: [
        {
          name: '@@deny',
          args: [
            { name: 'operation', value: ExpressionUtils.literal('all') },
            {
              name: 'condition',
              value: ExpressionUtils.binary(
                ExpressionUtils.call('auth'),
                '==',
                ExpressionUtils._null(),
              ),
            },
          ],
        },
        {
          name: '@@allow',
          args: [
            { name: 'operation', value: ExpressionUtils.literal('all') },
            {
              name: 'condition',
              value: ExpressionUtils.binary(
                ExpressionUtils.member(ExpressionUtils.call('auth'), ['id']),
                '==',
                ExpressionUtils.field('authorId'),
              ),
            },
          ],
        },
        {
          name: '@@allow',
          args: [
            { name: 'operation', value: ExpressionUtils.literal('read') },
            { name: 'condition', value: ExpressionUtils.field('published') },
          ],
        },
      ],
      idFields: ['id'],
      uniqueFields: {
        id: { type: 'String' },
      },
    },
    Comment: {
      name: 'Comment',
      fields: {
        id: {
          name: 'id',
          type: 'String',
          id: true,
          attributes: [
            { name: '@id' },
            { name: '@default', args: [{ name: 'value', value: ExpressionUtils.call('cuid') }] },
          ],
          default: ExpressionUtils.call('cuid'),
        },
        createdAt: {
          name: 'createdAt',
          type: 'DateTime',
          attributes: [
            { name: '@default', args: [{ name: 'value', value: ExpressionUtils.call('now') }] },
          ],
          default: ExpressionUtils.call('now'),
        },
        updatedAt: {
          name: 'updatedAt',
          type: 'DateTime',
          updatedAt: true,
          attributes: [{ name: '@updatedAt' }],
        },
        content: {
          name: 'content',
          type: 'String',
        },
        post: {
          name: 'post',
          type: 'Post',
          optional: true,
          attributes: [
            {
              name: '@relation',
              args: [
                { name: 'fields', value: ExpressionUtils.array([ExpressionUtils.field('postId')]) },
                { name: 'references', value: ExpressionUtils.array([ExpressionUtils.field('id')]) },
                { name: 'onUpdate', value: ExpressionUtils.literal('Cascade') },
                { name: 'onDelete', value: ExpressionUtils.literal('Cascade') },
              ],
            },
          ],
          relation: {
            opposite: 'comments',
            fields: ['postId'],
            references: ['id'],
            onUpdate: 'Cascade',
            onDelete: 'Cascade',
          },
        },
        postId: {
          name: 'postId',
          type: 'String',
          optional: true,
          foreignKeyFor: ['post'],
        },
      },
      idFields: ['id'],
      uniqueFields: {
        id: { type: 'String' },
      },
    },
    Profile: {
      name: 'Profile',
      fields: {
        id: {
          name: 'id',
          type: 'String',
          id: true,
          attributes: [
            { name: '@id' },
            { name: '@default', args: [{ name: 'value', value: ExpressionUtils.call('cuid') }] },
          ],
          default: ExpressionUtils.call('cuid'),
        },
        createdAt: {
          name: 'createdAt',
          type: 'DateTime',
          attributes: [
            { name: '@default', args: [{ name: 'value', value: ExpressionUtils.call('now') }] },
          ],
          default: ExpressionUtils.call('now'),
        },
        updatedAt: {
          name: 'updatedAt',
          type: 'DateTime',
          updatedAt: true,
          attributes: [{ name: '@updatedAt' }],
        },
        bio: {
          name: 'bio',
          type: 'String',
        },
        age: {
          name: 'age',
          type: 'Int',
          optional: true,
        },
        user: {
          name: 'user',
          type: 'User',
          optional: true,
          attributes: [
            {
              name: '@relation',
              args: [
                { name: 'fields', value: ExpressionUtils.array([ExpressionUtils.field('userId')]) },
                { name: 'references', value: ExpressionUtils.array([ExpressionUtils.field('id')]) },
                { name: 'onUpdate', value: ExpressionUtils.literal('Cascade') },
                { name: 'onDelete', value: ExpressionUtils.literal('Cascade') },
              ],
            },
          ],
          relation: {
            opposite: 'profile',
            fields: ['userId'],
            references: ['id'],
            onUpdate: 'Cascade',
            onDelete: 'Cascade',
          },
        },
        userId: {
          name: 'userId',
          type: 'String',
          unique: true,
          optional: true,
          attributes: [{ name: '@unique' }],
          foreignKeyFor: ['user'],
        },
      },
      idFields: ['id'],
      uniqueFields: {
        id: { type: 'String' },
        userId: { type: 'String' },
      },
    },
  } as const
  typeDefs = {
    CommonFields: {
      name: 'CommonFields',
      fields: {
        id: {
          name: 'id',
          type: 'String',
          attributes: [
            { name: '@id' },
            { name: '@default', args: [{ name: 'value', value: ExpressionUtils.call('cuid') }] },
          ],
          default: ExpressionUtils.call('cuid'),
        },
        createdAt: {
          name: 'createdAt',
          type: 'DateTime',
          attributes: [
            { name: '@default', args: [{ name: 'value', value: ExpressionUtils.call('now') }] },
          ],
          default: ExpressionUtils.call('now'),
        },
        updatedAt: {
          name: 'updatedAt',
          type: 'DateTime',
          updatedAt: true,
          attributes: [{ name: '@updatedAt' }],
        },
      },
    },
  } as const
  enums = {
    Role: {
      values: {
        ADMIN: 'ADMIN',
        USER: 'USER',
      },
    },
  } as const
  authType = 'User' as const
  plugins = {}
}
export const schema = new SchemaType()
